apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-service-account
  namespace: backstage
  labels:
    owner: platform
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: true
