apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: backstage
  labels:
    owner: platform
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true

