apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.serviceFullName }}-service-account
  labels:
    owner: ${{ values.team }}
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
