apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../applicationSet

helmCharts:
  - name: platform
    releaseName: platform-applicationsets-dev
    valuesFile: ../../applicationSet/platform/values.yaml
    additionalValuesFiles:
      - ../../applicationSet/platform/values-dev.yaml

  - name: workloads
    releaseName: workloads-applicationsets-dev
    valuesFile: ../../applicationSet/workloads/values.yaml
    additionalValuesFiles:
      - ../../applicationSet/workloads/values-dev.yaml
