apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-sa
  namespace: team-a
  labels:
    owner: team-a
    app.kubernetes.io/part-of: team-a
    app.kubernetes.io/managed-by: platform
automountServiceAccountToken: false

