apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-level components (ingress, infra services)

  # Allowed source repositories (Git + Helm)
  sourceRepos:
    - git@github.com:kurv1ts/platform-engineering.git
    - https://helm.traefik.io/traefik
    - https://kubernetes-sigs.github.io/external-dns/

  # Single cluster, any namespace
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  # Allowed cluster-scoped resources (STRICT, REQUIRED)
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: gateway.networking.k8s.io
      kind: GatewayClass
    - group: networking.k8s.io
      kind: IngressClass

  # Allow all namespaced resources
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
