apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Workload applications

  sourceRepos:
    - git@github.com:kurv1ts/platform-engineering.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  namespaceResourceWhitelist:
    - group: "apps"
      kind: "Deployment"
    - group: "apps"
      kind: "StatefulSet"
    - group: "apps"
      kind: "DaemonSet"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "ConfigMap"
    - group: "autoscaling"
      kind: "HorizontalPodAutoscaler"
    - group: "policy"
      kind: "PodDisruptionBudget"
    - group: "gateway.networking.k8s.io"
      kind: "HTTPRoute"
