apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Workload applications

  sourceRepos:
    - https://github.com/kurv1ts/platform-engineering
    - https://github.com/kurv1ts/platform-scaffolded-api.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret

    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet

    - group: batch
      kind: Job
    - group: batch
      kind: CronJob

    - group: networking.k8s.io
      kind: Ingress

    - group: autoscaling
      kind: HorizontalPodAutoscaler
