apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: node24-template
  title: Nodejs v24 Template
  description: An example template for the scaffolder that creates a node v24 application.
spec:
  owner: group:platform
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Component information
      required:
        - name
      properties:
        name:
          title: Component name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Repository details
      required:
        - team
        - repo
      properties:
        team:
          title: Team
          type: string
          description: Team that owns the service
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group
        repo:
          title: Repository name
          type: string

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: https://github.com/kurv1ts/platform-engineering/tree/main/templates/node
        values:
          serviceFullName: ${{ parameters.team | parseEntityRef | pick('name') }}-${{ parameters.repo }}
          team: ${{ parameters.team | parseEntityRef | pick('name') }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        # Hardcoded owner for now, should create custom action for this
        repoUrl: github.com?owner=kurv1ts&repo=${{ parameters.team | parseEntityRef | pick('name') }}-${{ parameters.repo }}
        defaultBranch: "main"
        topics: ["idp-managed", "node24", "team-${{ parameters.team | parseEntityRef | pick('name') }}"]
        repoVisibility: public

    # Custom action for updating catalog-info.yaml. Next step registers the component in the catalog
    - id: updateCatalogInfo
      name: update-catalog-info
      action: template:catalog-info-handler
      input:
        repoUrl: github.com?owner=kurv1ts&repo=${{ parameters.team | parseEntityRef | pick('name') }}-${{ parameters.repo }}
        team: ${{ parameters.team }}
        componentName: ${{ parameters.name }}

    # The final step is to register the new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
