apiVersion: v1
kind: PersistentVolume
metadata:
  name: backstage-postgres-storage
  namespace: backstage
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgres-storage-claim
  namespace: backstage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
