---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-postgres-secrets
  namespace: backstage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgALBsuLdKBIErr93BqxR3xercCiqhpxQDNK1HPOcixaNQ+yWJy7Ptje7vB1TEyuKXK+Pp9pquPv0711RWbXI4ADTXZuGPCZtxsGnjFng1CJ8Wf5M4+A0SduubnG6Tds3WURE1eoBzpO0HYEWpITVNxctHt89RxQ9ljmrDiptfIMGfmX6Y38eDcH2cTQzV195TRsbd9wNSZ6gMJrYU4jFbYnhlXZ7+UJkJEYyVyiPkcPhVFYQhdOmqeWV2QUtOPIE/Fz7ddCrVZr6NGh11JuSalOHRE6xycCspzB6sqxoA6XFoYfDKu8wQtMr1KV61wdKLSq81Fw+nidmAgAB1c2JE6a8Vvnz1cw2vxfkIMjHowV01pYS3PlfI2jXqcJz3iFhrfsP6DbyIr3EKuswJKaG0LkBNK9e/9lks55X6+HW58Un5HzGXqey10EuQg85ZEY6H6I8zR0ZJ8XPihtamPEMilDIPfnKvGdbtRpxuxNvvvi730xKZ46Vv0PCeKkeTocqC4VGakkOrGrHm77Y/SO4QfcEWkPu1wYQL/gYju9rAbNMBb4C1Nhkjmp3XsxCdlLyzYxk8XcxV38LLcX8yAOZS6xBHi52tI7+GOVtP0/XOzykmrfnQiGxWyW1YNZkQUB5tVxpBOSVGE7HpHjORF/bEquYkykPv9TbQC4HNZiMKdWJfO6h7j0a2qCLFDmVS+LiRofarBSjXYn9SEj
    POSTGRES_USER: AgA3gQecZU7ig+1XxSPzRrp3voawZeE9U+jDxxDQyu2QoCF3hdncVehijyaqz/rh0fs+d3OW1UrLsvOWgHhWOOS+fNVIbVSPJfuKAK2bLT3O5CxCyU6pG2FUIsYapGTYn6NRDre5nCtyr3xDGagXN8BlkX5jIJ2FKYXZ0S097aDNvxEeXxQg/q9UrBUuJbagD0bOh3oyDQeO2cMjTFLbRbcBZ2N2T0Qzk4sCqxPp9c1mSTbGw1UlXdE3g/2QWjZd5ervjHDk3u4TmlqL7MxUuxXdWEbnbhFi5dEBmonS1S34aglLSULVGo75dbPRwp3iujDO8eSpog/fu1+bI0RLXDxgp42m/PbPHAizjKKmTZaZF76iaP4n9WHQv10dFtheYZFtiD/vxHCVzR+XZUSbWnaUPMwOnvequgtGLI9xnSAs4C86gpqydWX26rGbGyM4RMYktB0bXiLSQvdiTCXOWRlbz975r26ajwnyR0EVHdYF9MngkRicA2y60H/5WHCYLAB2DdJDhJpdRFVXTNuOh2n9FLNtuZGYkI9OioVI8hG0aSVF+WtqAlxKYue6PEbuhzdPC6SF4vC9F+P0JmBbMAeZIahNm7+F8LAdx1WNjYp/ZNVfsGT6/N/xLrMpqgNloQZ5PV2YRPqcN8s9hSzkw1XqAeAFBYl+0iuvQyFtkSYqMLwzIGOJiHHHoNjmppdoxPXXZENVPfr2rMigaec=
  template:
    metadata:
      name: backstage-postgres-secrets
      namespace: backstage
    type: Opaque
