apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backstage-postgres
  namespace: backstage
spec:
  serviceName: backstage-postgres
  replicas: 1
  selector:
    matchLabels:
      app: backstage-postgres
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1" #Deploy first (before the backstage application)
      labels:
        app: backstage-postgres
    spec:
      nodeSelector:
        role: platform
      containers:
        - name: postgres
          image: postgres:16.11-alpine3.23
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: backstage-postgres-secrets
          env:
            - name: POSTGRES_HOST
              value: backstage-postgres.backstage
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: postgresdb
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2G

