apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami-service-account
  namespace: whoami
  labels:
    owner: platform
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argocd