
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../argo/applicationSet

helmCharts:
  - name: platform
    releaseName: platform-applicationsets-dev
    valuesFile: ../../argo/applicationSet/platform/values.yaml
    additionalValuesFiles:
      - ../../argo/applicationSet/platform/values-dev.yaml

  - name: workloads
    releaseName: workloads-applicationsets-dev
    valuesFile: ../../argo/applicationSet/workloads/values.yaml
    additionalValuesFiles:
      - ../../argo/applicationSet/workloads/values-dev.yaml
