---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-postgres-secrets
  namespace: backstage-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBE0Hk47QSdkflQteTMJXi9E10r+AKcpM7vt2pLpkxu8FXxRQvdBkcL43MamrM+rf4cBi3t8IC7FCmeflwBKsz4UAGtw6GaddR9ERB/RpSAJXZcvo28YXn3zJTistj6E8AEDX+6gSZgPLRcnViDi1wFxoWPb/sEDOsRaFRqJA9wrJ/3C1TokLe7tUmM5QETI+eioTqAVh20HN0eHOZH2Pnlzyo0NFIE944oQG/B4q9AA/cOxRvwT/ciRy6JnCqqzOwV8PQ8Sit1eyXM0LPqtkMG4XFS1AXGZmxT8bo9Lty9qldQP8XOCYnaajemDcpCyuFIU3XnjgmZJVjC7bv+bgrwjnTawcG8zzUz0zg+YDRJ8M5z2KurSY6M9YY+fscvLEri2OQqVA++y+okZKoVP1kpq+s15U/PgvRotlT+PLcOVOQvdFFvtZSqjj0WTQnMPAfzCxYX1jJsLE4WqvLF3lJZU6VBb4gJqvSJMmLs6/AYhBiKH6qB+Wv9MaoyJ7JOZlDIhW3U7bNlcSdH7h3rK4DMs+MrJOsaPPE4WAGXx5NON+hGTblzx4A9xXtEWqtXBjdDqgJdd8td0xDDI2jVuBCwA7clTC4NP55sOt8CquSpV7zicp5QC/se4XigABnXf5PdivyfxVgfwokvUfOypkybHXygSn7HJrUWdG/bI74EuhyV9QaCpyOxhBTpkLYWtwTpc3bQzJ5bIKYdOJCKL18o
    POSTGRES_USER: AgDAZQpwTrvnoM89s7YrlQGEiIjlsI6VBzkmpWuOuiuZfvmwPyVlZzso9GHxO82O8QKx+EaqcipsKT/L2ZcTSKAQIHzg2svmkwIUOCEvWfpk5LRiNNtUw2zQflOm8ZNC+oFqfWsv0+kL5ty1JgeorE7/IqYY/s3i0aXSl4JtyP43tsh70hDG48i9ihiAQeZO6F+vemTMNVfWzqxLe2/WdfRUnRIuo0zwvR4lVrAOvEz1WZHKxVJryH5eNiy8IJ7VXxOSKumRzubYDvBQEWqjXMfM7A51wodR+4/1x5h9Utgu3KIywILw+8QAChSrGHKvdyRdMtS66pU+zY3pfDBIFmvMTAh8jXcuBnXeuLoWsqUsSwanAUL+UH51QEzXJWhojhEFFWzmwW0sP5uki7iP2T8cQpcZ04K+pdNiS88JC2zrsCrAl27/oSlsUqs0JqD37XnHTAJwHMpyN5o3XxAYt2ep9r53lWfuC0zXhS3y6J3NDe8Rmes8dR7sWp2Yn0gZQ06mFDZNBIuDF9BQaW00U+truai4GoiTR+BdeomwgGTI5n2yG6mgQDZgq2LdlD2LTbLf6VWzNX/X9DStPr2vvLlIdIMTreNvLlIvz5fGGpgC1M9+2Oi3Gb4N5hm8Conr5mBsBs1WplSXDvXCHEgcFxmZ7OYwi+y8q2D8IUXhtp79yyhlD+ukZ2lR+r47YJNK2guAMi4xXGdz45g3LA==
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: platform
        owner: platform
      name: backstage-postgres-secrets
      namespace: backstage-dev
    type: Opaque
