apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        revision: main
        directories:
          - path: gitops/apps/platform/backstage/overlays/*
  template:
    metadata:
      name: "backstage-{{.path.basename}}"
      annotations:
        argocd.argoproj.io/sync-wave: "2" #Deployment order
    spec:
      project: platform
      source:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: backstage-{{.path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
