apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        revision: main
        files:
          - path: "gitops/apps/platform/sealed-secrets/overlays/*/sealed-secrets.yaml"

  template:
    metadata:
      name: "sealed-secrets-{{env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"

    spec:
      project: platform
      source:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        targetRevision: main
        path: gitops/apps/platform/sealed-secrets/overlays/{{env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
