apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        revision: main
        directories:
          - path: gitops/apps/platform/sealed-secrets/overlays/*

  template:
    metadata:
      name: "sealed-secrets-{{.path.basename}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"

    spec:
      project: platform
      source:
        repoURL: git@github.com:kurv1ts/platform-engineering.git
        targetRevision: main
        path: "{{.path.path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: sealed-secrets-{{.path.basename}}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
