apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: default

  template:
    metadata:
      name: "sealed-secrets"
      annotations:
        argocd.argoproj.io/sync-wave: "0"

    spec:
      project: platform
      sources:
      - repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: sealed-secrets
        targetRevision: 2.18.0
        helm:
          releaseName: sealed-secrets
          valueFiles:
            - $values/gitops/apps/platform/sealed-secrets/values/values.yaml
      - repoURL: git@github.com:kurv1ts/platform-engineering.git
        targetRevision: main
        ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: sealed-secrets

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            owner: platform
            app.kubernetes.io/part-of: platform
            app.kubernetes.io/managed-by: argocd
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
