apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read-only
  labels:
    owner: platform
    app.kubernetes.io/part-of: backstage
    app.kubernetes.io/managed-by: argocd
subjects:
  - kind: ServiceAccount
    name: backstage-service-account
    namespace: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
